language: c

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install -y gcc
    - sudo apt-get install -y libgtk-3-dev

script:
    - make
