language: c

install:
    - sudo add-apt-repository -y ppa:gnome3-team/gnome3
    - sudo apt-get update
    - sudo apt-get install -y gnome-platform-devel

script:
    - ./configure
    - touch configure.ac aclocal.m4 configure Makefile.am Makefile.in
      # Because a git clone messes all timestamps
    - make
