language: c

before_install:
    - echo deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update

install:
    - sudo apt-get install automake check
    - sudo apt-get install -y -t trusty gnome-platform-devel

script:
    - make
