language: c

install:
    - sudo apt-get update
    - sudo apt-get install -y gnome-platform-devel

script:
    - ./configure
    - touch aclocal.m4
      # Because a git clone messes all timestamps
    - make
