language: c

install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install -y gcc-4.8
    - export CC=gcc-4.8
    - sudo apt-get install -y gnome-platform-devel

script:
    - make -B
