language: c

install:
    - echo deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get install -y -t trusty gnome-platform-devel

script:
    - ./configure
    - touch configure.ac aclocal.m4 configure Makefile.am Makefile.in
      # Because a git clone messes all timestamps
    - make
